### ISSUE TITLE
I dont want anything,i guess i am bipolar,I guess u are not that safe around me,I guess youll be fine,I guess Ill be fine,but it is too much uk,itll take so much time to forget u.I hope u dont take much time to forget me because i am shitty anyway me peaving will release u.I wish to god that something really bad happens to me to compensate all the bad thing i have done to you,I am totally devastated and hopeless and cluesless,everyone feels like new people,i want you so bad i want you but i dont want to say this becuase i am literally blown apart cant talk cant breathe I am in very much discomfort,i love you only and it is paining very much pls do something i will not hurt u i want to talk to u only pls its paining very much

### ISSUE THREAD

**Issue by Prianshu-git** [AnannaB/githubtest#2]

**Comment by AnannaB** [comment]
Sorry I can’t help!! Please talk to your parents..whatever happened it’s
all because of you … you have to let me go this time cause everything is
ruined! Amay joto galagal ditish chokh mukh bujhe mene nitam but ebar amar
dada k diyechish onek kichu kharap hoyegeche please it’s a request nije
thik thakar chestha kor amio korchi but I don’t wanna talk to you at all
..i am so so sorryy please I can’t talk to you! I have to think about
myself now sorry

**Comment by Prianshu-git** [comment]
Please please once once ia m really really im dying

**Comment by Prianshu-git** [comment]
Please re please i am really dying anannna

**Comment by Prianshu-git** [comment]
Pain pain pain ananaa plssss

**Comment by Prianshu-git** [comment]
Please, On, please, it is paining, please please. It is paining. It is very much paining.

**Comment by Prianshu-git** [comment]
Khub bethaa

**Comment by Prianshu-git** [comment]
Anannaa

**Comment by Prianshu-git** [comment]
Paining paining

**Comment by Prianshu-git** [comment]
Pls pls plsss

**Comment by Prianshu-git** [comment]
Please pleaseee
